### ISSUE TITLE
Cannot fetch 'refs/heads/master'

### ISSUE THREAD

**Issue by mnicky** [mkottman/lua-git#1]
`git.protocol.fetch` can't fetch the `master` branch.

E.g. when executing [test_fetch.lua](https://github.com/mkottman/lua-git/blob/master/test_fetch.lua):

<pre>
$ bin/lua ~/tmp/test_fetch.lua
$ bin/lua: .../Repository/_install/bin/../lib/lua/git/protocol.lua:82: Server does not have refs/heads/master
stack traceback:
    [C]: in function 'error'
    .../Repository/_install/bin/../lib/lua/git/protocol.lua:82: in function 'git_fetch'
    .../Repository/_install/bin/../lib/lua/git/protocol.lua:124: in function 'fetch'
    ~/tmp/test_fetch.lua:10: in main chunk
    [C]: ?
</pre>

For other branches, e.g. [branch `parallel_fetch` of  luadist-git](https://github.com/mnicky/luadist-git/tree/parallel_fetch) it works as expected.

**Comment by mkottman** [comment]
Fixed in 46af76218035b977628aa8980da2913cdbf83736

**Comment by mnicky** [comment]
Thank you.
