### ISSUE TITLE
cannot fetch under Windows

### ISSUE THREAD

**Issue by mnicky** [mkottman/lua-git#3]
Even after making the creating of directories portable (see my [pull request](https://github.com/mkottman/lua-git/pull/4)), I'm getting errors when trying to fetch some repository under Windows (tested just on virtual installation of Windows XP)...

E.g. if I modify the `test_fetch.lua` file to this (btw, is the _package_ part correct?):

<pre>
package.path = package.path .. ';lua\\?.lua'
package.cpath = package.cpath .. ';b\\?.so'

require 'git'

os.execute('rd /S /Q C:\\tmp\\test.git')
os.execute('rd /S /Q C:\\tmp\\extracted')

R = git.repo.create('C:\\tmp\\test.git')
local pack, sha = git.protocol.fetch('git://github.com/mkottman/lua-git.git', R, 'refs/heads/master')
R:commit(sha):checkout('C:\\tmp\\extracted')
</pre>

and when I run it, I get:

<pre>
C:\luadist\_install>bin\lua.exe ..\lua-git\test_fetch.lua
Counting objects: 30, done.
Compressing objects: 100% (29/29), done.
Total 30 (delta 3), reused 22 (delta 1)
bin\lua.exe: InvalidInput: input string does not conform to zlib format or check
sum failed at C:\luadist\_install\tmp\lua-git-0.2\src\zlib.c line 182
stack traceback:
        [C]: in function 'z'
        C:\luadist\_install\bin\..\lib\lua\git\pack.lua:70: in function 'uncompress_by_len'
        C:\luadist\_install\bin\..\lib\lua\git\pack.lua:166: in function 'read_object'
        C:\luadist\_install\bin\..\lib\lua\git\pack.lua:296: in function 'open'
        C:\luadist\_install\bin\..\lib\lua\git\protocol.lua:114: in function 'git_fetch'
        C:\luadist\_install\bin\..\lib\lua\git\protocol.lua:125: in function 'fetch'
        ..\lua-git\test_fetch.lua:10: in main chunk
        [C]: ?
</pre>

**Comment by mkottman** [comment]
Please try commit 51c46ba0d28b018889dfc12d5f674723ed4da67b. It opens and writes all files in binary mode (no '\n' <=> '\r\n' translation for Windows). I guess this is the issue, but I cannot test it now.

**Comment by mnicky** [comment]
Yes, it was probably the problem, because now it gives me another error :) Another bug report soon :)

**Comment by mnicky** [comment]
...so, now it gives me this error under Windows:

<pre>
bin\lua.exe: C:\luadist\_install\bin\..\lib\lua\git\repo.lua:95: bad argument #1 to 'concat' (table expected, got nil)
stack traceback:
        [C]: in function 'concat'
        C:\luadist\_install\bin\..\lib\lua\git\repo.lua:95: in function 'commit'
        ..\lua-git\test_fetch.lua:11: in main chunk
        [C]: ?
</pre>

The reason is that [`commit.message`](https://github.com/mkottman/lua-git/blob/53b52b7e12ec75a93f68ca9808393f890418b24c/lua/git/repo.lua#L95) is `nil`, which is caused by the fact, that the branch [`elseif line == ''`](https://github.com/mkottman/lua-git/blob/53b52b7e12ec75a93f68ca9808393f890418b24c/lua/git/repo.lua#L90) is never true under Windows, because of this:

**While under Linux, the values of variable [`line`](https://github.com/mkottman/lua-git/blob/53b52b7e12ec75a93f68ca9808393f890418b24c/lua/git/repo.lua#L73) are (respectively):**
- for repo `git://github.com/LuaDist/Repository.git`:

```
tree 085f20be40e6b1aa8e8f4c235fc8616059c35b87
parent 83b0e37b56e3255776878300b7c6b77de7436085
author Peter Drahoš <drahosp@gmail.com> 1356619790 +0100
committer Peter Drahoš <drahosp@gmail.com> 1356619790 +0100

Updated submodules
```
- and for repo `git://github.com/mkottman/lua-git.git`:

```
tree 5e6e08b3ddaad8dd20db675535c8c5f4eada4751
parent 51c46ba0d28b018889dfc12d5f674723ed4da67b
author Michal Kottman <michal.kottman@gmail.com> 1357685579 +0100
committer Michal Kottman <michal.kottman@gmail.com> 1357685579 +0100

Handle commits for submodules in a tree, fix #2

Previously, only 'blob' and 'tree' objects were handled in a tree.
When a git repository contains submodules, they are stored in the tree
as a 'commit object' (mode 16000). While checking out the tree, an
empty directory is created for each such commit.
```

**...under Windows, the values of the [`line`](https://github.com/mkottman/lua-git/blob/53b52b7e12ec75a93f68ca9808393f890418b24c/lua/git/repo.lua#L73) variable are:**
- for repo `git://github.com/LuaDist/Repository.git`:

```
tree 085f20be40e6b1aa8e8f4c235fc8616059c35b87
parent 83b0e37b56e3255776878300b7c6b77de7436085
author Peter Drahos╠î <drahosp@gmail.com> 1356619790 +0100
c
```

(...that `c` isn't typo :)
- and for repo `git://github.com/mkottman/lua-git.git`:

```
tree 5e6e08b3ddaad8dd20db675535c8c5f4eada4751
parent 51c46ba0d28b018889dfc12d5f674723ed4da67b
author Michal Kottman <michal.kottman@
```

...so it seems that part of the file [`f`](https://github.com/mkottman/lua-git/blob/53b52b7e12ec75a93f68ca9808393f890418b24c/lua/git/repo.lua#L68) is lost under Windows. However, the value of the variable `len` is the same under Windows and under Linux (235 and 533 respectively for those two repos).

Here I stopped with my debugging....

**Comment by mkottman** [comment]
I'll have to get my Windows XP virtual machine up an running... This seems like data corruption or encoding issues, I don't know definitely.

**Comment by mkottman** [comment]
Okay, I made a [typo](http://programovani.tumblr.com/post/40023045315/kdyz-hledate-bug-prochazite-kod-az-ten-preklep) when opening file for binary reading - I didn't actually open one file in binary mode, which caused data truncation. Please try out commit 2e5ca2dc94fd7a3c8df60aa2c76bf566fdf6b4ec to see if it works.

![](http://eu3.memecdn.com/when-my-boss-tells-me-to-come-to-work-on-weekendss_o_851005.gif)

**Comment by mnicky** [comment]
Works like a charm :)
