### ISSUE TITLE
Cannot install batteries under Windows: too many open files

### ISSUE THREAD

**Issue by mnicky** [mkottman/lua-git#8]
When trying to install `batteries` with luadist-git under Windows, I'm getting an error about too many open files from `git-lua`:

```
C:\luadist\_install\_test\_new>bin\luadist.exe _source install batteries
Finding out available versions of batteries...
Getting batteries-0.9.7 (source)...
Finding out available versions of lua...
Getting lua-5.1.5 (binary)...
Finding out available versions of luadist-git...
Getting luadist-git-0.2.1 (binary)...
Finding out available versions of luafilesystem...
Getting luafilesystem-1.6.2 (binary)...
Finding out available versions of srlua...
(...)
Finding out available versions of unzip...
Getting unzip-6.0 (binary)...
Finding out available versions of zip...
Getting zip-3.0 (binary)...
Finding out available versions of iup...
Getting iup-3.6 (binary)...
Getting batteries-0.9.6 (source)...
Cannot install package 'batteries': Error when retrieving the info about 'batteries': Error fetching package batteries-0.9.6' from 'git://github.com/LuaDist/batteries.git' to 'C:\luadist\_install\_test\_new\_source\tmp': ...dist\_install\_test\_new\bin\..\lib\lua\git\repo.lua:186: C:\luadist\_install\_test\_new\_source\tmp\batteries-0.9.6\.git/HEAD: Too many open files
```

When downloading the package (in [package.fetch_pkg()](https://github.com/mnicky/luadist-git/blob/master/dist/package.lua#L358)), `luadist-git` itself doesn't open any files, so I think that the bug will be probably in `lua-git`.

---

I found a few file handles in `lua-git` source, that don't _seem_ to be explicitly closed. As I don't know the internals of `lua-git` very well, I don't know which ones could be closed and which not. So I'm providing just their list, which might be at least of a little help:

file handles returned from io.open():
- [objects.lua:86](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/objects.lua#L86)
- [pack.lua:276](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/pack.lua#L276)
- [pack.lua:277](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/pack.lua#L277)
- [repo.lua:215](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/repo.lua#L215)
- [repo.lua:230](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/repo.lua#L230)
- [util.lua:93](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/util.lua#L93)

file handles returned from io.tmpfile():
- [pack.lua:99](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/pack.lua#L99)

file handles returned from other functions:
- [repo.lua:68](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/repo.lua#L68) - variable `f`
- [repo.lua:101](https://github.com/mkottman/lua-git/blob/f22812935053827df52d26d5e27125d139ded954/lua/git/repo.lua#L101) - variable `f`

**Comment by mkottman** [comment]
Yes there are a lot of unclosed files. I will try to close as many as possible, and document where the closing is left for the user.
